name: Cleanup after PR

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest

    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

    - name: Install test CLI
      run: ${{ github.event.number }}



