export const filters = [
	{ label: "Estado", items: ["Novas", "Usadas"] },
	{
		label: "Marca",
		items: [
			"Lumak",
			"Lanmax",
			"Jack",
			"SunSpecial",
			"Juki",
			"Brother",
			"Zoje",
			"SunStar",
			"Yamata",
			"Nippon",
			"Kansai",
			"Bracob",
			"Siruba",
		],
	},
	{
		label: "Tipo",
		items: [
			"Overlock",
			"Reta",
			"Galoneira",
			"Elastiqueira",
			"Travete",
			"Botoneira",
			"Caseadeira",
			"Elastiqueira",
			"Pesponta-deira",
			"Ombro a ombro",
			"Fechadeira de braço",
			"Máquina de corte",
		],
	},
	{ label: "Fios", items: ["1", "2", "3", "4"] },
];
