export const filters = [
  { label: "Estado", items: ["Novas", "Usadas"] },
  {
    label: "Marca",
    items: [
      "Lumak",
      "Lanmax",
      "Jack",
      "SunSpecial",
      "Juki",
      "Brother",
      "Zoje",
      "SunStar",
      "Yamata",
      "Nippon",
      "Kansai",
      "Bracob",
      "Siruba",
    ],
  },
  {
    label: "Tipo",
    items: [
      "Overlock",
      "Reta",
      "Galoneira",
      "Elastiqueira",
      "Travete",
      "Botoneira",
      "Caseadeira",
      "Elastiqueira",
      "Pesponta-deira",
      "Ombro a ombro",
      "Fechadeira de braço",
      "Máquina de corte",
    ],
  },
  { label: "Fios", items: ["1", "2", "3", "4"] },
];

export const resourcesFilters = [
  { label: "luz de led no cabeçote", icon: "" },
  { label: "posicionador de agulha", icon: "" },
  { label: "painel de controle", icon: "" },
  { label: "comando de voz", icon: "" },
  { label: "levantamento de calçador", icon: "" },
  { label: "corte de linha", icon: "" },
  { label: "retrocesso automático", icon: "" },
  { label: "parada de agulha", icon: "" },
  { label: "Calçador acionado por solenoide (suprime ruídos)", icon: "" },
];
