name: Preview environment workflow

on: pull_request

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test

    environment: Preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
